### ISSUE TITLE
Attemping to Restore to Android Tachiyomi app from iOS Tachimanga backup gives invalid backup file error

### ISSUE THREAD

**Issue by Nitrousoxide** [tachimanga/tachimanga.github.io#2]
Tachimanga can successfully restore from an android app's backup, but when attempting the reverse I get an error on the android app saying

```
Invalid Backup File
kotlinx.serialization.protobuf.internal.ProtobufDecodingException: Unsupported Start group or end group wire type: 3
```

It would be very nice to have backups that work bidirectionally, so you can pick up from where you left off on an iOS device on an android device.

**Comment by tachimanga** [comment]
Currently, only Tachiyomi -> Tachimanga is supported. Tachimanga -> Tachiyomi is not supported.
