### ISSUE TITLE
Myanimelist doesn’t show up

### ISSUE THREAD

**Issue by OrintalMrc** [tachimanga/tachimanga.github.io#3]
I just pay for the premium features on the app and now doesn’t show's when i want to search to sync my progress. Any way to solve it?
![IMG_1159](https://github.com/tachimanga/tachimanga.github.io/assets/74692815/6063565e-87ed-480e-b325-98138cbefd9d)
![IMG_1160](https://github.com/tachimanga/tachimanga.github.io/assets/74692815/5f8adc3f-ac69-4e10-a354-26a4f62f7212)
![IMG_1161](https://github.com/tachimanga/tachimanga.github.io/assets/74692815/e6735afe-d1ed-462b-b7f6-64f0c35fe312)

**Comment by tachimanga** [comment]
MAL API is temporarily down, and the MAL staff is currently working on
resolving the issue.


OrintalMrc ***@***.***>于2024年2月6日 周二08:17写道：
